### ISSUE TITLE
Getting this error on Raspberry Pi 4 using your guide for Raspbian OS

### ISSUE THREAD

**Issue by hasankhurshid29** [PINTO0309/mediapipe-bin#11]
root@raspberrypi:/usr/local/src/mediapipe/mediapipe-bin# sudo pip3 install \
cmake-3.20.2-cp37-none-linux_aarch64.whl \
numpy-1.20.3-cp37-none-linux_aarch64.whl \
mediapipe-0.8-cp37-none-linux_aarch64.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: cmake-3.20.2-cp37-none-linux_aarch64.whl is not a supported wheel on this platform.

**Comment by PINTO0309** [comment]
RaspberryPi OS (armv7l) is not supported.
