### ISSUE TITLE
ubuntu 21.04   not a supported wheel

### ISSUE THREAD

**Issue by aliisaiid98** [PINTO0309/mediapipe-bin#2]
I'm using ubuntu 21.04  64bit desktop in a raspberry pi 4 and whenever I try 

sudo pip3 install \
opencv_contrib_python-4.5.2.52-cp38-none-linux_aarch64.whl \
mediapipe-0.8-cp38-none-linux_aarch64.whl

I get this error:
"ERROR: opencv_contrib_python-4.5.2.52-cp38-none-linux_aarch64.whl is not a supported wheel on this platform."
any ideas on how to solve this? thanks in advance

**Comment by PINTO0309** [comment]
Sorry. I made a mistake with the file name and confused you. Please try to download the necessary resources again using this file.
https://github.com/PINTO0309/mediapipe-bin/blob/main/v0.8.4/numpy120x/mediapipe-0.8-cp39-none-linux_aarch64_numpy120x_ubuntu2104_download.sh
5cb7ccc652e94aeb7793258ec16fd4df3b5566b0

**Comment by aliisaiid98** [comment]
> @aliisaiid98
> Sorry. I made a mistake with the file name and confused you. Please try to download the necessary resources again using this file. Pull the cloned repository again to update it to the latest version.
> 
> * The state of my wrong file name.
>   https://github.com/PINTO0309/mediapipe-bin/blob/main/v0.8.4/numpy120x/mediapipe-0.8-cp39-none-linux_aarch64_numpy120x_ubuntu2004_download.sh
> * correct
>   https://github.com/PINTO0309/mediapipe-bin/blob/main/v0.8.4/numpy120x/mediapipe-0.8-cp39-none-linux_aarch64_numpy120x_ubuntu2104_download.sh
> 
> [5cb7ccc](https://github.com/PINTO0309/mediapipe-bin/commit/5cb7ccc652e94aeb7793258ec16fd4df3b5566b0)

thanks for the fast response but unfortunately I still got the same error although I deleted the mediapipe-bin file and cloned it again since you've modified it.

**Comment by PINTO0309** [comment]
It's a little strange. If I download directly from this link now, does it download the file opencv_contrib_python-4.5.2.52-cp39-cp39m-linux_aarch64.whl?
- opencv_contrib_python-4.5.2.52-cp39-cp39m-linux_aarch64.whl
https://drive.google.com/uc?export=download&confirm=${CODE}&id=1cZJy-lMvygqdBRiZMXbIRnduuEpSJJ26

**Comment by PINTO0309** [comment]
The build specification of opencv_python changes daily, so I decided to stop providing it. Use the following command to install it.
```
$ sudo pip3 install opencv_contrib_python
```

**Comment by aliisaiid98** [comment]
> The build specification of opencv_python changes daily, so I decided to stop providing it. Use the following command to install it.
> ```
> $ sudo pip3 install opencv_contrib_python
> ```
I just saw your YouTube video, I guess i'll try it on raspian 64bit, thanks alot❤️

**Comment by aliisaiid98** [comment]
> > The build specification of opencv_python changes daily, so I decided to stop providing it. Use the following command to install it.
> > ```
> > $ sudo pip3 install opencv_contrib_python
> > ```
> I just saw your YouTube video, I guess i'll try it on raspian 64bit, thanks alot❤️

It worked from the first try, Many thanks
