### ISSUE TITLE
jetson nano CSI camera Not working

### ISSUE THREAD

**Issue by niladridmgit** [PINTO0309/mediapipe-bin#3]
Thank you for your effort to make such excellent stuff like this. I am able to use usb camera in jetson Nano and all sample codes are working without any issue but after this installation now my CSI camera codes are not working. getting camera not open error. I am using below gstreamer code for CSI camera in jetson nano

def create_gstreamer_pipeline(
        self,
        sensor_id=0,
        sensor_mode=3,
        display_width=640,
        display_height=480,
        framerate=30,
        flip_method=2,
    ):
        self._gstreamer_pipeline = (
            "nvarguscamerasrc sensor-id=%d sensor-mode=%d ! "
            "video/x-raw(memory:NVMM), "
            "format=(string)NV12, framerate=(fraction)%d/1 ! "
            "nvvidconv flip-method=%d ! "
            "video/x-raw, width=(int)%d, height=(int)%d, format=(string)BGRx ! "
            "videoconvert ! "
            "video/x-raw, format=(string)BGR ! appsink"
            % (
                sensor_id,
                sensor_mode,
                framerate,
                flip_method,
                display_width,
                display_height,
            )
        )

**Comment by PINTO0309** [comment]
I'm a beginner with the Jetson Nano and have only been using it for 3 days, so I've never used a CSI camera with gstreamer. So there is no way to predict what kind of error message you are encountering. What should I look for? There is too little information available for my skills, and I don't know where to start looking.

This is not a joke, I'm serious.

**Comment by niladridmgit** [comment]
Hi Thanks for your very quick reply. Yes I am able to solve the issue. I 1st uninstall opencv_contrib_python-4.5.2.52 package (sudo pip3 uninstall opencv_contrib_python-4.5.2.52-cp36-none-linux_aarch64.whl) then rebuild opencv 4.5.2 from fresh (https://qengineering.eu/install-opencv-4.5-on-jetson-nano.html) now i am able to use mediapipe in jetson nano using CSI camera without any issue.

**Comment by PINTO0309** [comment]
Thank you for sharing, I found that I can increase the performance by enabling gstreamer along with CUDA enabled build of OpenCV. I will rebuild the installer. Thanks! :smile_cat:

**Comment by niladridmgit** [comment]
Thank you. I shall test with CSI cam and update you soon

**Comment by niladridmgit** [comment]
Hi getting below error

sudo pip3 install opencv_contrib_python-4.5.2.52-cp36-none-linux_aarch64.whl
WARNING: The directory '/home/niladri/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing ./opencv_contrib_python-4.5.2.52-cp36-none-linux_aarch64.whl
ERROR: opencv-contrib-python has an invalid wheel, .dist-info directory 'opencv_python-4.5.2.52.dist-info' does not start with 'opencv-contrib-python

**Comment by PINTO0309** [comment]
@niladridmgit I tried experimenting with opencv with gstreamer enabled and mediapipe without opencv_contrib_python, but I kept getting segmentation faults and could not get it to work properly.

- opencv_python-4.5.2.54-cp36-cp36m-linux_aarch64.whl
- mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl
https://drive.google.com/drive/folders/1swZYxgfFaVy2HF61MegGFswoBwvKxrq1?usp=sharing

**Comment by PINTO0309** [comment]
The build specification of opencv_python changes daily, so I decided to stop providing it.

**Comment by niladridmgit** [comment]
Hi sorry for delay. gstreamer  take more memory if I open 2 instance using 2 CSI cam due to memory overflow I am getting segmentation faults but 1 CSI working good in my Jetson Nano 4gb (B01) model which support 2 CSI cam

**Comment by PINTO0309** [comment]
Probably A02 (4GB). However, I don't have a CSI camera that can be used with the Jetson Nano... :crying_cat_face: Segmentation Fault occurs when checking the operation using a USB camera.
![Nvidias-Jetson-Nano-packs-quite-a-punch-in-a-small-package-including-both-the-Nano-module-and-a-carrier-board-with-plenty-of-IO-options](https://user-images.githubusercontent.com/33194443/121290831-3dedd580-c922-11eb-9d84-328086a6a35f.jpg)
