### ISSUE TITLE
Curl: command not found

### ISSUE THREAD

**Issue by Niclasp1501** [PINTO0309/mediapipe-bin#5]
i cant download the whl-files.

(mediatest) npjetson@npjetson-desktop:~/mediapipe-bin$ ./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh
./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh: line 3: curl: command not found
awk: cannot open /tmp/cookie (No such file or directory)
./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh: line 5: curl: command not found
./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh: line 11: curl: command not found
awk: cannot open /tmp/cookie (No such file or directory)
./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh: line 13: curl: command not found
Download finished.

**Comment by PINTO0309** [comment]
sudo apt install curl
