### ISSUE TITLE
I can't build mediapipe because: "Genrules without outputs don't make sense"

### ISSUE THREAD

**Issue by hungnk1992** [PINTO0309/mediapipe-bin#6]
Dear supporter,

When I try to build mediapipe on jetson xavier dev kit. I have problem as below
Could you please take a look and provide your support?

Thanks,

DEBUG: /home/hungnk19922022/.cache/bazel/_bazel_hungnk19922022/be00561a79348da2361bf34f036a476e/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "02413e4a077107711ecc21458432e7c9ba63e75e63f3fa84ae4da2d6b2c82700"
DEBUG: Repository rules_cc instantiated at:
  /home/hungnk19922022/wk/tools/mediapipe/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  /home/hungnk19922022/.cache/bazel/_bazel_hungnk19922022/be00561a79348da2361bf34f036a476e/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1ed6f5b02a7baf14daca04817566e7c98ec668cec381e0edf534fa49f10f58a2"
DEBUG: Repository opencv instantiated at:
  /home/hungnk19922022/wk/tools/mediapipe/WORKSPACE:181:13: in <toplevel>
Repository rule http_archive defined at:
  /home/hungnk19922022/.cache/bazel/_bazel_hungnk19922022/be00561a79348da2361bf34f036a476e/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/hungnk19922022/.cache/bazel/_bazel_hungnk19922022/be00561a79348da2361bf34f036a476e/external/local_config_python/BUILD:69:8: in outs attribute of genrule rule @local_config_python//:python_include: Genrules without outputs don't make sense
ERROR: Analysis of target '//mediapipe/python:_framework_bindings.so' failed; build aborted: Analysis of target '@local_config_python//:python_include' failed

**Comment by PINTO0309** [comment]
You don't provide any information about the environment you ran it in or the commands you ran, so I can't guess anything. Also, I don't own a jetson xavier so I can't try it.

And most importantly, I'm not interested.
